config/routes.rb
Blog::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"},
                     path_names: {sign_in: "home"}

  match '/users/auth:provider' => 'omniauth_callbacks#passthru', method: :get
  match '/users/auth/:provider/callback' => 'omniauth_callbacks#passthru', method: :get

  root :to => "home#welcome"

  resources :projects
  resources :orders do
    member do
      get "accept"
      get "finish"
      get "revise"
    end
  end

  resources :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!#, except: [:welcome]


    def index
    #@values_for_select = Service.values_for_select
    #@projects = Project.where(:user_id => current_user.id)
  end


  def welcome
    if user_signed_in?
    	@completed = Project.where(:user_id => current_user.id,
    		:project_status => "Completed")
    	@inProgress = Project.where(:user_id => current_user.id,
    		:project_status => "In Progress")
    	@projects = Project.where(:user_id => current_user.id)

    	@pending = Order.where(:user_id => current_user.id,
    		:status => "Pending")
    	@current_orders = Order.where(:user_id => current_user.id,
    		:status => "In Progress")
    	@completed_orders = Order.where(:user_id => current_user.id,
    		:status => "Completed")

      if current_user.category.blank? or current_user.category.nil?
        redirect_to edit_user_registration_path
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<html>
<head>

	<title>JOBberWORKy: Student Job Order Request Site</title>
	<%= stylesheet_link_tag    "userhome", :media => "all" %>
	<!-- <#%= javascript_include_tag "userhome" %> -->
	<%= csrf_meta_tags %>
</head>
<%content_for :projhist do %>
<% unless user_signed_in? %>
<!-- NOT SIGNED IN -->
<%= link_to (image_tag "Home/JOBORDERbuttoncopy.png", :size => "300x300"), "/orders/new" %>
<h1>HELLO THEEEREEEE ~(-_-~)</h1>
<% else %>
<!-- SIGNED IN -->

<h1>Project History</h1>
<h2>Pending</h2>
<% if !@project.nil? && @project.status == "Pending" %>
<div class="CSSTableGenerator" >
  <table >
    <tr>
      <td>Project Id</td>
      <td>Category</td>
      <td>Title</td>
      <td>Description</td>
      <td>Link</td>
    </tr>
    <% @projects.each do |project| %>
    <tr>
      <td ><%= project.id %></td>
      <td><%= project.category.name %></td>
      <td><%= project.title %></td>
      <td><%= project.description %></td>
      <td><%= project.project_link %></td>
    </tr>
    <% end %>
  </table>
</div>
<% else %>
You have no pending projects.
<% end %>

<h2> In Progress</h2>
<% if !@project.nil? && @project.status == "In Progress" %>
<div class="CSSTableGenerator" >
  <table >
    <tr>
      <td>Project Id</td>
      <td>Category</td>
      <td>Title</td>
      <td>Description</td>
      <td>Link</td>
    </tr>
    <% @projects.each do |project| %>
    <tr>
      <td ><%= project.id %></td>
      <td><%= project.category.name %></td>
      <td><%= project.title %></td>
      <td><%= project.description %></td>
      <td><%= project.project_link %></td>
    </tr>
    <% end %>
  </table>
</div>
<% else %>
You have no projects in progress.
<% end %>

<h2>Completed</h2>
<% if !@project.nil? && @project.status == "Completed" %>
<div class="CSSTableGenerator" >
  <table >
    <tr>
      <td>Project Id</td>
      <td>Category</td>
      <td>Title</td>
      <td>Description</td>
      <td>Link</td>
    </tr>
    <% @projects.each do |project| %>
    <tr>
      <td ><%= project.id %></td>
      <td><%= project.category.name %></td>
      <td><%= project.title %></td>
      <td><%= project.description %></td>
      <td><%= project.project_link %></td>
    </tr>
    <% end %>
  </table>
</div>
<% else %>
You have not completed any projects yet.<br>
<% end %>

<%end%>
<%end%>

<%= link_to "Request new", "/projects/new" %>

app/views/home/welcome.html.erb
<script>
jQuery(function() {
  $("a.fancybox").fancybox();
});
</script>
<div style="margin-bottom:50px;width:90%; padding-top:20px">
  <div class="container">
    <div class="offset1" style="box-shadow:0px 0px 10px #050505">
      <div style="padding:10px; background: #20815d; height: 100px; color: #fff;">
        <div style="float:left">
          <% if !current_user.image_url.nil? %>
            <%= image_tag current_user.image_url, :style => "height: 100px" %>
          <% else %>
            <%= image_tag "no_avatar.png", :style => "height: 100px" %>
          <% end %>
        </div>
        <div style="float:left">
          <h2><%= current_user.first_name %> <%= current_user.surname %></h2>
          <h4 style="padding-left: 20px"><%=link_to 'View Profile', user_path(id: current_user.id) %> | <%= link_to ' Edit Profile', edit_user_registration_path %></h4>
        </div>
      </div>
      <div style="padding:5px; background: #fff;">
        <div class="container">
          <ul class="nav nav-tabs offset3" style="font-family:Oswald; width: 700px;">
              <li><a href="#2" data-toggle="tab">JOB ORDER HISTORY</a></li>
              <li><a href="#3" data-toggle="tab">PERSONAL PORTFOLIO</a></li>
              <li><a href="#1" data-toggle="tab">ADD TO Y0UR PORTFOLIO</a></li>
              <li><a href="#4" data-toggle="tab">SUBMIT A JOB ORDER</a></li>
              <li><a href="#55" data-toggle="tab">INTERNALS FORM</a></li>
          </ul>
        </div>
          <div class="tab-content">

            <div class="tab-pane active" id="2">
              <div>
                <div class="tabbable-fixed-top">
                  <ul class="nav nav-pills">
                    <li style="padding-top:10px; padding-left:10px;" class="active"><a href="#5" data-toggle="tab">Pending <%= "(#{@pending.length})" %></a></li>
                    <li style="padding-top:10px"class=""><a href="#6" data-toggle="tab">In Progress</a></li>
                    <li style="padding-top:10px" class=""><a href="#7" data-toggle="tab">Completed</a></li>
                  </ul>
                  <div class="tab-content">
                    <div class="tab-pane active" id="5">
                      <div class="span9">
                        <% if @pending.count > 0 %>
                          <% @pending.in_groups_of(3, false).each do |group| %>
                            <% group.each do |project| %>
                              <div class="span3" style="float: left; width: 220px; overflow: hidden; background-color: white; padding: 20px; margin-bottom: 10px;">
                                <div class="title"><%= link_to project.project_name, "/orders/#{project.id}" %></div>
                                <div class="ic_category"><%= project.category.name %></div>
                                <b>Requested by:</b> <%= project.first_name %> <%= project.surname %><br>
                                <b>Target date:</b> <%= project.target_date.strftime("%b %d, %Y") %><br>
                                <table><tr><td>
                                  <%= link_to accept_order_path(id: project.id) do %><button> Accept </button><% end %></td><td>
                                  <%= link_to order_path(id: project.id), :confirm => "Are you sure?", :method => :delete do%><button> Reject </button><% end %>
                                </td></tr></table>
                              </div>
                            <% end %>
                          <% end %>
                        <% else %>
                          <div style="margin-bottom: 20px">You have no pending job requests. Hooray!</div>
                        <% end %>
                      </div>
                    </div>
                    <div class="tab-pane" id="6">
                      <div class="span9">
                        <% if @current_orders.count > 0 %>
                          <% @current_orders.in_groups_of(4, false).each do |group| %>
                            <% group.each do |project| %>
                              <div class="span3" style="float: left; width: 220px; overflow: hidden; background-color: white; padding: 20px; margin-bottom: 10px;">
                                <% if project.image_url.nil? %>
                                  <%= link_to (image_tag "inprogress.png", :title=>project.project_name,
                                  :id=>"capslide_img_cont1"), "inprogress.png",
                                  {:id =>"capslide_img_cont1", :class => "fancybox"} %>
                                <% else %>
                                  <%= link_to (image_tag project.image_url, :title=>project.project_name,
                                  :id=>"capslide_img_cont1"), "inprogress.png",
                                  {:id =>"capslide_img_cont1", :class => "fancybox"} %>
                                <% end %>
                                <div class="ic_category"><%= project.category.name %></div>
                                <div class="title"><%= link_to project.project_name, "/orders/#{project.id}" %></div>
                                <b>Requested by:</b> <%= project.first_name %> <%= project.surname %><br>
                                <b>Target date:</b> <%= project.target_date.strftime("%b %d, %Y") %><br>
                                <%= link_to finish_order_path(id: project.id) do %><button> Finish </button><% end %>
                              </div>
                            <% end %>
                          <% end %>
                        <% else %>
                          <div style="margin-bottom: 20px">You have no job requests currently in progress.</div>
                        <% end %>
                      </div>
                    </div>
                    <div class="tab-pane" id="7">
                      <div class="span9">
                      <% if @completed_orders.count > 0 %>
                          <% @completed_orders.in_groups_of(3, false).each do |group| %>
                            <% @completed_orders.each do |project| %>
                              <div class="span3" style="float: left; width: 220px; overflow: hidden; background-color: white; padding: 20px; margin-bottom: 10px;">
                                <% if !project.image_url.nil? %>
                                  <%=link_to (image_tag project.image_url, :title=>project.project_name, :id=>"capslide_img_cont1", :class=>"fancybox", :style => "width: 300px;"), project.image_url, {:id =>"capslide_img_cont1", :class => "fancybox"} %>
                                <% else %>
                                  <%=link_to (image_tag "goojab.gif", :title=>project.project_name, :id=>"capslide_img_cont1", :class=>"fancybox"), "goojab.gif", {:id =>"capslide_img_cont1", :class => "fancybox"} %>
                                <% end %>
                                <div class="ic_category"><%= project.category.name %></div>
                                <div class="title"><%= link_to project.project_name, "/orders/#{project.id}" %></div>
                                <b>Requested by:</b> <%= project.first_name %> <%= project.surname %><br>
                                <b>Target date:</b> <%= project.target_date.strftime("%b %d, %Y") %><br>
                                <%= link_to revise_order_path(id: project.id) do %><button> Revise this project </button><% end %>
                              </div>
                            <% end %>
                          <% end %>
                        <% else %>
                          <div style="margin-bottom: 20px">You have not completed any job requests yet. Get to work!</div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="3">
              <div class="span10">
                <% if @projects.count > 0 %>
                  <% @completed.in_groups_of(4, false).each do |group| %>
                    <% group.each do |project| %>
                      <%=link_to(project.project_link) do%>
                        <span><div class="span3" style="float: left; overflow: hidden; background-color: rgb(219,219,219); padding: 5px; margin-bottom: 10px; margin-top: 10px; border-radius: 5px;">
                        <% if !project.image_url.nil? %>
                          <%=link_to (image_tag project.image_url, :title=>project.title, :id=>"capslide_img_cont1", :class=>"fancybox", :style => "width: 300px;"), project.image_url, {:id =>"capslide_img_cont1", :class => "fancybox"} %>
                        <% else %>
                          <% if project.project_status == "In Progress" %>
                            <%=link_to (image_tag "inprogress.png", :title=>project.title, :id=>"capslide_img_cont1", :class=>"fancybox"), "inprogress.png", {:id =>"capslide_img_cont1", :class => "fancybox"} %>
                          <% elsif project.project_status == "Completed" %>
                            <%=link_to (image_tag "goojab.gif", :title=>project.title, :id=>"capslide_img_cont1", :class=>"fancybox"), "goojab.gif", {:id =>"capslide_img_cont1", :class => "fancybox"} %>
                          <% end %>
                        <% end %>
                        <div class="ic_category"><%= project.category.name %></div>
                        <div class="title"><%= link_to project.title, "/projects/#{project.id}" %></div>
                        <%= link_to project.project_link, project.project_link %><br><br>
                        </div>
                        </span>
                      <% end %>
                    <% end %>
                  <%end%>
                <% else %>
                  <div style="margin-bottom: 20px">You have not uploaded any projects yet. <%= link_to "Upload one now!", new_project_path %></div>
                <% end %>
              </div>
            </div>
            <div class="tab-pane" id="4">
              <%= render "orders/form" %></div>
            </div>
            <div class="tab-pane" id="55">
              <%= render "orders/iform" %></div>
            </div>
            <div class="tab-pane" id="1">
                <div class="span10" style="margin-bottom: 10px;background:#ff8500">
                <div class="span offset2" style=" background-image: url(orange.png);background:white; padding-left:40px">

              <%= form_for(:project, :url => {:controller => 'projects', :actions => 'create', :method => :post}, :html => {:multipart => true}) do |f|%> <br>
              <table>
                <tr><td>
                  CREATED BY:</td><td> <%= f.collection_select(:user_id, User.where(:id => current_user.id), :id, :first_name, :readonly => true, :disabled => true) %></td></tr>
                  <tr><td>Category </td><td><%= f.collection_select(:category_id, Category.where(:id => current_user.category.id), :id, :name, :readonly => true, :disabled => true) %></td></tr>
                  <tr><td>Image </td><td><%= f.file_field :image %></td></tr>
                  <tr><td>Title</td><td> <%= f.text_field :title %></td></tr>
                  <tr><td>Description</td><td> <%= f.text_area :description, :style => "height: 100px;" %></td></tr> <br>
                  <tr><td> Link</td><td> <%= f.text_field :project_link %></td></tr>
                  <tr><td>Status</td><td> <%= f.radio_button :project_status, "In Progress" %> In Progress <%= f.radio_button :project_status, "Completed" %> Completed</td></tr>
              </table>
<br>
              <center>
                <%= f.submit "Submit" %>
            </center>
            <% end %>

        </div>
    </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="haha" style=" font-size: 10px;height:25px; position: fixed; width:100%; bottom:0">
  <div class="offset11">All rights reserved. Chos.</div>
</div>

<script type="text/javascript" src="jquery-1.3.2.js"></script>
<script src="jquery.capSlide.js" type="text/javascript"></script>
<script type="text/javascript">
  $(function() {
    $("#capslide_img_cont1").capslide({
      caption_color: 'white',
      caption_bgcolor: 'black',
      overlay_bgcolor: 'black',
      border: '',
      showcaption: false
    });
</script>
<script>
  $(elementID).capslide()
</script>