config/routes.rb
Blog::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"},
                     path_names: {sign_in: "home"}

  match '/users/auth:provider' => 'omniauth_callbacks#passthru', method: :get
  match '/users/auth/:provider/callback' => 'omniauth_callbacks#passthru', method: :get

  root :to => "home#welcome"

  resources :projects
  resources :orders do
    member do
      get "accept"
      get "finish"
      get "revise"
    end
  end

  resources :users

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :image_cache, :category_id, :description, :project_link, :title, :user_id, :project_status, 
  								:image, :remove_image, :image_url

  belongs_to :user
  belongs_to :category
  #has_many :orders

  mount_uploader :image, ImageUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project])
		#@user = User.find_by_id(@project.user_id)
		#if @user != nil
			if @project.save
				flash[:notice] = 'Your project was successfully created.'
				redirect_to root_path
			else
				flash[:notice] = 'Error! Your project was not saved.'
				render "new"
			end
		#else
			#flash[:notice] = 'Error! Your project was not saved, sorry.'
			#render "new"
		#end
	end

	def edit
		@project = Project.find params[:id]
	end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      flash[:notice] = "Your project was successfully updated."
      redirect_to project_path(@project)
    else
      flash[:notice] = "Failed to update"
    end
  end

  def destroy
  	@project = Project.find(params[:id])
  	@project.destroy
  	redirect_to root_path
  end

	def index
		@user = User.find(params[:id])
	end

	def show
		@project = Project.find(params[:id])
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<tr><td><%= form_for(@project, :html => {:multipart => true}) do |f|%> </td></tr>
<tr><td>Created by </td><td><%= f.collection_select(:user_id, User.where(:id => current_user.id), :id, :first_name, :readonly => true, :disabled => true) %> </td></tr>
<tr><td>Category </td><td><%= f.collection_select(:category_id, Category.where(:id => current_user.category.id), :id, :name, :readonly => true, :disabled => true) %> </td></tr>
<tr><td>Image </td><td width="100px"><%= f.file_field :image %></td></tr>
<tr><td>Title </td><td><%= f.text_field :title %> </td></tr>
<tr><td>Description </td><td><%= f.text_area :description, :style => "height: 100px;" %> </td></tr>
<tr><td>Link </td><td><%= f.text_field :project_link %> </td></tr>
<tr><td>Status </td><td><%= f.radio_button :project_status, "In Progress" %> In Progress <%= f.radio_button :project_status, "Completed" %> Completed</td></tr>
<tr><td><%= f.submit "Submit" %></td><td><%end%><%= button_to "Cancel", root_path %></td></tr>

app/views/projects/edit.html.erb
<div style="margin-bottom:50px;width:90%; padding-top:20px">
	<div class="container">
		<div class="offset1">
			<div style="padding:10px; background: #20815d; height: 50px; color: #fff;">
				<h1>New Project</h1>
				<hr>
      </div>
			<div style="color: #000;padding:5px; background: #e4e4e4;">
				<table>
        	<%= render "form" %>
      	</table>
      </div>
		</div>
	</div>
</div>
<div class="haha" style=" font-size: 10px;height:25px; position: fixed; width:100%; bottom:0">
	<div class="offset11">All rights reserved. Chos.</div>
</div>

app/views/projects/index.html.erb
Hi <%= @project.title %>

app/views/projects/new.html.erb
<%= render "form" %>

app/views/projects/show.html.erb
<div style="margin-bottom:50px;width:90%; padding-top:20px">
	<div class="container">
		<div class="offset1">
			<div style="padding:10px; background: #20815d; height: 80px; width: 95%; color: #fff; float: center;">
				<h1><%= @project.title %></h1>
				<div class="title">by <%= @project.user.first_name %> <%= @project.user.surname %> | <%= @project.created_at.strftime("%b %d, %Y") %></div>
				<hr>
			</div>
			<div style="color: #000;padding:10px; background: #e4e4e4; width: 95%; height: 350px;">
				<table>
					<tr>
						<td>
							<% if !@project.image_url.nil? %>
	              <%= image_tag @project.image_url, :style => "height: 350px;" %><br><br>
	            <% else %>
	              <% if @project.project_status == "In Progress" %>
	                <%= image_tag "inprogress.png", :style => "height: 350px;" %><br><br>
	              <% elsif @project.project_status == "Completed" %>
	                <%= image_tag "goojab.gif", :style => "height: 350px;" %><br><br>
	              <% end %>
	            <% end %>
	          </td>
						<td style="vertical-align:top;" class="span6">
							<b>Status:</b> <%= @project.project_status %><br><br>
							<b>Description:</b><br><%= @project.description %><br><br>
							<b>Link:</b> <%= link_to @project.project_link, @project.project_link %><br><br>
							<div align="right"><%= link_to edit_project_path(@project) do %><button> Edit </button><% end %>
								<%= link_to project_path(@project), :confirm => "Are you sure? There is no undo!", :method => :delete do%><button> Delete </button><% end %>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="haha" style=" font-size: 10px;height:25px; position: fixed; width:100%; bottom:0">
	<div class="offset11">All rights reserved. Chos.</div>
</div>